### PR TITLE
Add rate limits

### LINKED ISSUE #8: Rate Limits
The Slack API docs have [descriptions of 4 primary tiers of rate limits](https://api.slack.com/docs/rate-limits) (plus some special cases), and then each method lists its limit. I did something yesterday that hit the limit, and that was annoying. I knew it would probably take a long time, but I had to program around the limit myself. I realized... we can build that in!

As far as I've found, the limits are (mostly) per method, so this technique should keep Slack happy most of the time.

We could add an optional argument to `post_slack`, something like "rate_limit", an integer number of calls per minute. If it's included, we add information to the `.slack` environment about that method's rate limit, what minute we're "in" for this method, and how many calls the user has made to it this minute. If the limit has been reached for the current minute, we sleep until the following minute, reset the count, and reset the minute. It's better for us to build this in directly, because we can increment the count properly if we make multiple calls in the course of a single function call (ie, if we use `paginate_`).

For any methods we implement directly, we can include the `rate_limit`, but we can leave it as a parameter that users can adjust (by calling `post_slack` directly) if they want to try to burst and that sort of thing.

If that all sounds reasonable, I'll implement this (and remove the hacked version from my code).

### PR DESCRIPTION
**Pull request by jonthegeek**
Closes #8.

### CODE REVIEW

**Comment by jonthegeek** [comment]
Tests work locally.

Most of the GHA fail due to changes in the underlying actions/the caching. I'm not going to fix that completely in this PR, most likely.

R-mac and R-win actually ran the tests, and THEN they failed. I'm attempting to get those ones to work as part of this PR, at least.

**Comment by jonthegeek** [comment]
Doh, not yet! I still get a "too many requests" error when I use this in practice. Thinking.

**Comment by jonthegeek** [comment]
Ok, NOW it works!

**Comment by yonicd** [comment]
Frustrating, those runners are failing because your user cant “see” the secrets. Groundhogs day

**Comment by jonthegeek** [comment]
Yeah, I tried adding equivalent secrets to my fork, but no luck. I'm having a similar problem with some r4ds stuff. I think I might have to make a dev branch that people PR into, and then run the checks only on PR into main... But that would mean I merge into dev without knowing, so that doesn't seem right. Maybe there's a permission on the secret somewhere?

**Comment by jonthegeek** [comment]
Hardening tests to work without API available.

**Comment by jonthegeek** [comment]
@yonicd All of the GHA except `shield` run properly now. I'm not sure how that works so I'm not sure how to fix that one/if it can be fixed. Would it be ok to set that one to only run on merge (since all the other tests have to have passed at that point)?

**Pull request merged**
